---
all:  # Группа хостов
  children:  # Обозначение, что будет подгруппа хостов
    linux:
      children:
        proxy:
          hosts:  # Узлы группы
            example-ubuntu-24-vm3-proxy:  # Имя машины
              ansible_host: 84.201.128.245  # Адрес машины
        nginx:  # Имя подгруппы хостов
          hosts:  # Узлы группы
            example-ubuntu-24-vm1:  # Имя машины
              ansible_host: 89.169.147.115  # Адрес машины
            example-ubuntu-24-vm2:  # Имя машины
              ansible_host: 84.201.174.115  # Адрес машины
  vars:  # Переменные, доступные или используемые для всех подгрупп
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
